### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by Tsuesun**
Update!

### CODE REVIEW

**Comment by Tsuesun** [comment]
There is no conflict with master on this one that needed to be resloved (I believe our changes are in `ts-fork` branch)

**Comment by ehats** [comment]
I see some commits from Jesper in here - are those from upstream?

**Comment by Tsuesun** [comment]
> I see some commits from Jesper in here - are those from upstream?

Yep, that is correct

**Review by ehats — APPROVED** [review]

**Comment by Tsuesun** [comment]
@JesperTerkelsen Can you have a look at this when you have a chance?

**Review by JesperTerkelsen — APPROVED** [review]

**Pull request merged**
